services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    image: sujalpanwar/bsn-api:latest
    platform: linux/arm64
    environment:
      EMAIL_HOST_NAME: "${EMAIL_HOST_NAME}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_USER_NAME: "${EMAIL_USER_NAME}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres


  bsn-ui:
    container_name: bsn-ui
    image: sujalpanwar/bsn-ui:latest
    platform: linux/arm64
    ports:
      - 80:80
      - 443:443  # ← ADD HTTPS PORT
    volumes:
      - /etc/letsencrypt/live/readcircle.mine.bz/fullchain.pem:/etc/ssl/certs/readcircle.crt
      - /etc/letsencrypt/live/readcircle.mine.bz/privkey.pem:/etc/ssl/private/readcircle.key
    networks:
      - spring-demo
    depends_on:
      - bsn-api

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    platform: linux/arm64
    command:
      - start-dev
      - --http-enabled=true
      - --https-port=0
      - --import-realm
      - --proxy=edge  # ← ADD THIS FOR HTTPS PROXY
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: "edge"  # ← ADD THIS FOR HTTPS PROXY

    volumes:
      - /home/ubuntu/ReadCircle.json:/opt/keycloak/data/import/ReadCircle.json
    ports:
      - "9090:8080"
    networks:
      - spring-demo
    depends_on:
      - postgres

networks:
  spring-demo:
    driver: bridge



volumes:
  postgres:
    driver: local
