services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
#  mail-dev:
#    container_name: mail-dev-bsn
#    image: maildev/maildev
#    ports:
#      - 1080:1080
#      - 1025:1025
  bsn-api:
    container_name: bsn-api
    image: sujalpanwar/bsn-api:latest
    platform: linux/arm64
    environment:
      EMAIL_HOST_NAME: "${EMAIL_HOST_NAME}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_USER_NAME: "${EMAIL_USER_NAME}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres


  bsn-ui:
    container_name: bsn-ui
    image: sujalpanwar/bsn-ui:latest
    platform: linux/arm64
    ports:
      - 80:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    platform: linux/arm64
    command:
      - start-dev
      - --http-enabled=true
      - --https-port=0
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    volumes:
      - /home/ubuntu/ReadCircle.json:/opt/keycloak/data/import/ReadCircle.json
    ports:
      - "9090:8080"
    networks:
      - spring-demo
    depends_on:
      - postgres
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.1
#    container_name: keycloak
#    platform: linux/arm64
#    command:
#      - start-dev
#      - --http-enabled=true
#      - --https-port=0
#      - --import-realm
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HOSTNAME_STRICT: "false"
#      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
#    volumes:
#      - /home/ubuntu/ReadCircle.json:/opt/keycloak/data/import/ReadCircle.json
#    ports:
#      - "9090:8080"

    #  keycloak:
#    container_name: keycloak-bsn
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - 9090:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - spring-demo
#    command:
#      - "start-dev"

#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.1
#    container_name: keycloak
#    platform: linux/arm64
#    command:
#      - start-dev
#      - --import-realm
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    volumes:
#      - /home/ubuntu/ReadCircle.json:/opt/keycloak/data/import/ReadCircle.json
#    ports:
#      - "9090:8080"
networks:
  spring-demo:
    driver: bridge



volumes:
  postgres:
    driver: local
#  keycloak:
#    driver: local