spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
#    host: ${EMAIL_HOST_NAME}
#    port: 465
#    username: ${EMAIL_USER_NAME}
#    password: ${EMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 465
    username: sujalpanwar2001@gmail.com
    password: idsz bjcb ftjc khkd
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: "http://localhost:9090/realms/ReadCircle"
           issuer-uri: "http://144.24.124.183:9090/realms/ReadCircle"
server:
  port: 8088
# made few tweaks
application:
  security:

  cors:
    origins:

      # Public IP (HTTP + all ports)
      - http://141.148.222.231:*

      # Public IP (HTTPS + all ports, future SSL)
      - https://141.148.222.231:*

      # Public IP (HTTP + all ports)
      - http://144.24.124.183:*

      # Public IP (HTTPS + all ports, future SSL)
      - https://144.24.124.183:*

      # Local development (HTTP + all ports)
      - http://localhost:*
      - https://localhost:*

      - http://141.148.222.231
      - https://141.148.222.231
      - http://144.24.124.183
      - https://144.24.124.183
      - http://localhost:4200
      - http://localhost:8080



  file:
    uploads:
      photos-output-path: ./uploads



